### PR TITLE
feat: add table that displays top 100

### PR DESCRIPTION
**Pull request by ethmtrgt**
I added a table that displays top 100 cryptocurrencies.

### CODE REVIEW

**Comment by ethmtrgt** [comment]
Preview :point_down: 
Screenshot 2022-10-21 at 11-07-26 Crypto Rankings

**Review by eduardconstantin — CHANGES_REQUESTED** [review]
Could you remove the first 3 crypto from the table?

**Comment by ethmtrgt** [comment]
I made it using skip parameter in API. It should be 3+97 in its final view.

**Comment by eduardconstantin** [comment]
Nice, good job!

**Pull request merged**
